import { useMemo, useCallback, useState, useEffect } from 'react';
import {
  GitBranch as GitBranchIcon, GitCommitHorizontal, Check, CheckCircle2,
  Plus, Minus, Undo2, ChevronDown, ChevronRight, Loader2, RefreshCw,
  History, User, Trash2, GitMerge, FolderGit2, Eye, X, Sparkles,
} from 'lucide-react';
import { useIDEStore } from '../useIDEStore';
import { gitService } from '../engine/GitService';

// ── Helpers ───────────────────────────────────────────────────
const statusMeta = (s: string) => {
  switch (s) {
    case 'modified':  return { icon: 'M', color: '#fbbf24' };
    case 'added':     return { icon: 'A', color: '#22c55e' };
    case 'deleted':   return { icon: 'D', color: '#ef4444' };
    case 'untracked': return { icon: 'U', color: '#60a5fa' };
    default:          return { icon: '?', color: '#666' };
  }
};

const fileName = (fp: string) => fp.split('/').pop() ?? fp;
const dirPath  = (fp: string) => { const p = fp.split('/'); p.pop(); return p.join('/'); };

// ── Component ─────────────────────────────────────────────────
export function GitPanel() {
  const {
    currentTheme, sidebarWidth, addNotification,
    gitInitialized, gitBranch, gitStatuses, gitBranches, gitRealLog,
    initGit, refreshGitStatus, gitAddFile, gitAddAll,
    gitUnstageFile, gitUnstageAll, gitDiscardFile, gitCommit,
    gitCheckoutBranch, gitCreateBranch, gitDeleteBranch, gitDiffFile,
    generateCommitMsg,
  } = useIDEStore();

  const [commitMsg, setCommitMsg] = useState('');
  const [committing, setCommitting] = useState(false);
  const [initializing, setInitializing] = useState(false);
  const [stagedOpen, setStagedOpen] = useState(true);
  const [unstagedOpen, setUnstagedOpen] = useState(true);
  const [logOpen, setLogOpen] = useState(true);
  const [branchOpen, setBranchOpen] = useState(false);
  const [newBranch, setNewBranch] = useState('');
  const [diffFile, setDiffFile] = useState<string | null>(null);
  const [diffContent, setDiffContent] = useState<{ old: string; new: string } | null>(null);
  const [generating, setGenerating] = useState(false);

  // Split statuses into staged / unstaged
  const staged   = useMemo(() => gitStatuses.filter(f => f.staged), [gitStatuses]);
  const unstaged = useMemo(() => gitStatuses.filter(f => !f.staged), [gitStatuses]);

  // Auto-refresh on gitService events
  useEffect(() => {
    const unsub = gitService.onChange(() => refreshGitStatus());
    return unsub;
  }, [refreshGitStatus]);

  // ── Init handler ──
  const handleInit = useCallback(async () => {
    setInitializing(true);
    try { await initGit(); }
    finally { setInitializing(false); }
  }, [initGit]);

  // ── Commit handler ──
  const handleCommit = useCallback(async () => {
    if (!commitMsg.trim() || staged.length === 0) return;
    setCommitting(true);
    try {
      const sha = await gitCommit(commitMsg);
      if (sha) {
        addNotification({ type: 'success', message: `Committed ${sha.slice(0, 7)}` });
        setCommitMsg('');
      }
    } finally { setCommitting(false); }
  }, [commitMsg, staged.length, gitCommit, addNotification]);

  // ── Auto-generate commit message via AI ──
  const handleAutoMsg = useCallback(async () => {
    setGenerating(true);
    try {
      const msg = await generateCommitMsg();
      if (msg) {
        setCommitMsg(msg);
        addNotification({ type: 'success', message: 'Commit message generated by Niyah AI' });
      } else {
        addNotification({ type: 'warning', message: 'Could not generate message — is Ollama connected?' });
      }
    } finally { setGenerating(false); }
  }, [generateCommitMsg, addNotification]);

  // ── Diff viewer ──
  const openDiff = useCallback(async (filepath: string) => {
    const d = await gitDiffFile(filepath);
    if (d) { setDiffFile(filepath); setDiffContent(d); }
    else { addNotification({ type: 'info', message: 'No diff available (new file or binary)' }); }
  }, [gitDiffFile, addNotification]);

  // ── Not initialized state ──
  if (!gitInitialized) {
    return (
      <div
        className="h-full flex flex-col items-center justify-center select-none gap-3"
        style={{ width: sidebarWidth, backgroundColor: currentTheme.sidebar }}
      >
        <FolderGit2 size={36} style={{ color: currentTheme.textMuted, opacity: 0.3 }} />
        <p className="text-sm" style={{ color: currentTheme.textMuted }}>No git repository</p>
        <button
          className="text-xs px-4 py-1.5 rounded flex items-center gap-2 transition-opacity"
          style={{ backgroundColor: currentTheme.accent + '20', color: currentTheme.accent, opacity: initializing ? 0.5 : 1 }}
          disabled={initializing}
          onClick={handleInit}
        >
          {initializing ? <Loader2 size={12} className="animate-spin" /> : <GitBranchIcon size={12} />}
          Initialize Repository
        </button>
      </div>
    );
  }

  return (
    <div
      className="h-full overflow-y-auto select-none"
      style={{ width: sidebarWidth, backgroundColor: currentTheme.sidebar }}
      role="region"
      aria-label="Source Control"
    >
      {/* Header */}
      <div
        className="px-4 py-2 text-xs font-semibold uppercase tracking-wider flex items-center justify-between"
        style={{ color: currentTheme.textMuted }}
      >
        <span>Source Control</span>
        <button
          className="p-0.5 rounded hover:bg-white/10 transition-colors"
          title="Refresh"
          onClick={() => refreshGitStatus()}
        >
          <RefreshCw size={13} style={{ color: currentTheme.textMuted }} />
        </button>
      </div>

      {/* Commit input */}
      <div className="px-3 mb-2">
        <div className="relative">
          <input
            value={commitMsg}
            onChange={e => setCommitMsg(e.target.value)}
            placeholder={staged.length > 0 ? `Commit ${staged.length} staged file(s)…` : 'Stage files first…'}
            className="w-full bg-transparent border rounded px-2 py-1.5 pr-8 text-sm outline-none focus:ring-1 transition-shadow"
            style={{ borderColor: currentTheme.border, color: currentTheme.text }}
            onKeyDown={e => { if (e.key === 'Enter') handleCommit(); }}
          />
          <button
            className="absolute right-1.5 top-1/2 -translate-y-1/2 p-1 rounded hover:bg-white/10 transition-all"
            style={{ color: generating ? currentTheme.accent : currentTheme.textMuted }}
            title="Auto-generate commit message (Niyah AI)"
            disabled={generating || gitStatuses.length === 0}
            onClick={handleAutoMsg}
          >
            {generating
              ? <Loader2 size={13} className="animate-spin" />
              : <Sparkles size={13} />}
          </button>
        </div>
        <button
          className="w-full text-xs py-1.5 mt-1.5 rounded flex items-center justify-center gap-1.5 transition-opacity"
          style={{
            backgroundColor: currentTheme.accent + '20',
            color: currentTheme.accent,
            opacity: committing || !commitMsg.trim() || staged.length === 0 ? 0.4 : 1,
          }}
          disabled={committing || !commitMsg.trim() || staged.length === 0}
          onClick={handleCommit}
        >
          {committing ? <Loader2 size={12} className="animate-spin" /> : <Check size={12} />}
          Commit ({staged.length})
        </button>
      </div>

      {/* Branch bar */}
      <div
        className="px-3 py-1.5 flex items-center gap-2 text-xs border-t border-b cursor-pointer hover:bg-white/5 transition-colors"
        style={{ color: currentTheme.textMuted, borderColor: currentTheme.border + '40' }}
        onClick={() => setBranchOpen(o => !o)}
      >
        <GitBranchIcon size={13} style={{ color: currentTheme.accent }} />
        <span className="font-medium" style={{ color: currentTheme.text }}>{gitBranch || 'HEAD'}</span>
        <ChevronDown size={11} className={`ml-auto transition-transform ${branchOpen ? 'rotate-180' : ''}`} />
        <span className="tabular-nums">{gitStatuses.length} change{gitStatuses.length !== 1 ? 's' : ''}</span>
      </div>

      {/* Branch picker */}
      {branchOpen && (
        <div
          className="mx-3 my-1 rounded border p-2 text-xs"
          style={{ borderColor: currentTheme.border, backgroundColor: currentTheme.sidebar }}
        >
          {gitBranches.map(b => (
            <div
              key={b.name}
              className="flex items-center gap-2 py-1 px-1 rounded hover:bg-white/5 cursor-pointer transition-colors"
              style={{ color: b.current ? currentTheme.accent : currentTheme.text }}
              onClick={() => { if (!b.current) gitCheckoutBranch(b.name); setBranchOpen(false); }}
            >
              <GitBranchIcon size={11} />
              <span className="flex-1 truncate">{b.name}</span>
              {b.current && <Check size={11} />}
              {!b.current && b.name !== 'main' && b.name !== 'master' && (
                <button
                  className="opacity-40 hover:opacity-100 p-0.5"
                  title={`Delete ${b.name}`}
                  onClick={e => { e.stopPropagation(); gitDeleteBranch(b.name); }}
                >
                  <Trash2 size={10} />
                </button>
              )}
            </div>
          ))}
          <div className="flex gap-1 mt-1.5 pt-1.5 border-t" style={{ borderColor: currentTheme.border + '40' }}>
            <input
              value={newBranch}
              onChange={e => setNewBranch(e.target.value)}
              placeholder="new-branch"
              className="flex-1 bg-transparent border rounded px-1.5 py-0.5 text-xs outline-none"
              style={{ borderColor: currentTheme.border, color: currentTheme.text }}
              onKeyDown={e => {
                if (e.key === 'Enter' && newBranch.trim()) {
                  gitCreateBranch(newBranch.trim());
                  setNewBranch('');
                }
              }}
            />
            <button
              className="px-2 py-0.5 rounded text-xs transition-opacity"
              style={{ backgroundColor: currentTheme.accent + '20', color: currentTheme.accent, opacity: newBranch.trim() ? 1 : 0.4 }}
              disabled={!newBranch.trim()}
              onClick={() => { gitCreateBranch(newBranch.trim()); setNewBranch(''); }}
            >
              <GitMerge size={10} />
            </button>
          </div>
        </div>
      )}

      {/* Staged changes */}
      {staged.length > 0 && (
        <div className="mt-2" role="group" aria-label="Staged changes">
          <button
            className="w-full px-3 py-1 text-xs font-semibold flex items-center justify-between hover:bg-white/5 transition-colors"
            style={{ color: currentTheme.textMuted }}
            onClick={() => setStagedOpen(o => !o)}
          >
            <span className="flex items-center gap-1.5">
              {stagedOpen ? <ChevronDown size={12} /> : <ChevronRight size={12} />}
              Staged Changes
            </span>
            <span className="flex items-center gap-2">
              <span
                className="opacity-60 hover:opacity-100 p-0.5 cursor-pointer"
                title="Unstage All"
                onClick={e => { e.stopPropagation(); gitUnstageAll(); }}
              >
                <Minus size={12} />
              </span>
              <span className="opacity-60 tabular-nums">{staged.length}</span>
            </span>
          </button>
          {stagedOpen && staged.map(f => {
            const m = statusMeta(f.status);
            return (
              <div
                key={f.filepath}
                className="group flex items-center gap-2 px-4 py-1 text-sm cursor-pointer hover:bg-white/5 transition-colors"
                style={{ color: currentTheme.text }}
                onClick={() => openDiff(f.filepath)}
              >
                <span className="text-xs font-mono font-bold w-4 text-center shrink-0" style={{ color: m.color }}>{m.icon}</span>
                <span className="truncate flex-1 opacity-80">{fileName(f.filepath)}</span>
                <span className="text-xs opacity-40 truncate max-w-[40%]">{dirPath(f.filepath)}</span>
                <button
                  className="opacity-0 group-hover:opacity-70 hover:!opacity-100 p-0.5 rounded transition-opacity"
                  title="Unstage"
                  onClick={e => { e.stopPropagation(); gitUnstageFile(f.filepath); }}
                >
                  <Minus size={13} style={{ color: currentTheme.textMuted }} />
                </button>
              </div>
            );
          })}
        </div>
      )}

      {/* Unstaged changes */}
      {unstaged.length > 0 && (
        <div className="mt-2" role="group" aria-label="Changes">
          <button
            className="w-full px-3 py-1 text-xs font-semibold flex items-center justify-between hover:bg-white/5 transition-colors"
            style={{ color: currentTheme.textMuted }}
            onClick={() => setUnstagedOpen(o => !o)}
          >
            <span className="flex items-center gap-1.5">
              {unstagedOpen ? <ChevronDown size={12} /> : <ChevronRight size={12} />}
              Changes
            </span>
            <span className="flex items-center gap-2">
              <span
                className="opacity-60 hover:opacity-100 p-0.5 cursor-pointer"
                title="Stage All"
                onClick={e => { e.stopPropagation(); gitAddAll(); }}
              >
                <Plus size={12} />
              </span>
              <span className="opacity-60 tabular-nums">{unstaged.length}</span>
            </span>
          </button>
          {unstagedOpen && unstaged.map(f => {
            const m = statusMeta(f.status);
            return (
              <div
                key={f.filepath}
                className="group flex items-center gap-2 px-4 py-1 text-sm cursor-pointer hover:bg-white/5 transition-colors"
                style={{ color: currentTheme.text }}
                onClick={() => openDiff(f.filepath)}
              >
                <span className="text-xs font-mono font-bold w-4 text-center shrink-0" style={{ color: m.color }}>{m.icon}</span>
                <span className="truncate flex-1 opacity-80">{fileName(f.filepath)}</span>
                <span className="text-xs opacity-40 truncate max-w-[40%]">{dirPath(f.filepath)}</span>
                <div className="flex items-center gap-0.5 opacity-0 group-hover:opacity-70 transition-opacity">
                  <button className="hover:!opacity-100 p-0.5 rounded" title="Stage" onClick={e => { e.stopPropagation(); gitAddFile(f.filepath); }}>
                    <Plus size={13} style={{ color: currentTheme.textMuted }} />
                  </button>
                  <button className="hover:!opacity-100 p-0.5 rounded" title="Discard" onClick={e => { e.stopPropagation(); gitDiscardFile(f.filepath); }}>
                    <Undo2 size={13} style={{ color: currentTheme.textMuted }} />
                  </button>
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* Empty state */}
      {gitStatuses.length === 0 && (
        <div className="px-4 py-8 text-center" style={{ color: currentTheme.textMuted }}>
          <CheckCircle2 size={28} className="mx-auto mb-2 opacity-30" />
          <p className="text-sm opacity-60">Working tree clean</p>
        </div>
      )}

      {/* Inline diff viewer */}
      {diffFile && diffContent && (
        <div className="mx-3 my-2 rounded border overflow-hidden" style={{ borderColor: currentTheme.border }}>
          <div
            className="flex items-center justify-between px-2 py-1 text-xs"
            style={{ backgroundColor: currentTheme.border + '40', color: currentTheme.textMuted }}
          >
            <span className="flex items-center gap-1.5">
              <Eye size={11} />
              {fileName(diffFile)}
            </span>
            <button className="p-0.5 hover:bg-white/10 rounded" onClick={() => { setDiffFile(null); setDiffContent(null); }}>
              <X size={11} />
            </button>
          </div>
          <div className="grid grid-cols-2 gap-px text-xs font-mono overflow-auto max-h-48" style={{ backgroundColor: currentTheme.border + '20' }}>
            <div className="p-2 overflow-auto" style={{ backgroundColor: '#7f1d1d20', color: '#fca5a5' }}>
              <div className="text-[10px] opacity-50 mb-1">HEAD</div>
              <pre className="whitespace-pre-wrap break-all">{diffContent.old || '(empty)'}</pre>
            </div>
            <div className="p-2 overflow-auto" style={{ backgroundColor: '#14532d20', color: '#86efac' }}>
              <div className="text-[10px] opacity-50 mb-1">Working</div>
              <pre className="whitespace-pre-wrap break-all">{diffContent.new || '(empty)'}</pre>
            </div>
          </div>
        </div>
      )}

      {/* Commit log */}
      <div className="mt-4 px-3 pb-4">
        <button
          className="w-full text-xs font-semibold uppercase tracking-wider mb-2 flex items-center gap-1.5 hover:bg-white/5 rounded px-1 py-0.5 transition-colors"
          style={{ color: currentTheme.textMuted }}
          onClick={() => setLogOpen(o => !o)}
        >
          {logOpen ? <ChevronDown size={12} /> : <ChevronRight size={12} />}
          <History size={12} />
          Commit History ({gitRealLog.length})
        </button>
        {logOpen && gitRealLog.map(c => (
          <div
            key={c.hash}
            className="flex items-start gap-2 py-1.5 text-xs hover:bg-white/5 rounded px-1 transition-colors"
          >
            <GitCommitHorizontal size={13} className="mt-0.5 shrink-0" style={{ color: currentTheme.accent }} />
            <div className="flex-1 min-w-0">
              <div className="flex items-center gap-2">
                <span className="font-mono shrink-0 opacity-70" style={{ color: currentTheme.accent }}>{c.hash.slice(0, 7)}</span>
                <span className="truncate flex-1" style={{ color: currentTheme.text }}>{c.message}</span>
              </div>
              <div className="flex items-center gap-2 mt-0.5 opacity-50">
                <User size={10} />
                <span>{c.author}</span>
                <span>·</span>
                <span>{c.timeAgo}</span>
              </div>
            </div>
          </div>
        ))}
        {gitRealLog.length === 0 && (
          <p className="text-xs opacity-40 px-1" style={{ color: currentTheme.textMuted }}>No commits yet</p>
        )}
      </div>
    </div>
  );
}